### PR TITLE
fix: Zora NPC dialogue

### PR DESCRIPTION
**Pull request by anna-is-cute**
Edits below. All files are in EventFlowMsg.

# Npc_Zora036.msbt - talk12

**he -> she**

```
	OK... <null><null>In that case, give it a try!


For he who saved the domain,
this should be a piece of fish cake.<null>
Go on, I'm counting on you!
```

```
	OK... <null><null>In that case, give it a try!


For she who saved the domain,
this should be a piece of fish cake.<null>
Go on, I'm counting on you!
```

# Npc_Zora031.msbt - talk08

**Master Link -> Lady Linkle**

```
I mean...<null><null> Lady Linkle...


You and Lady Mipha fought <null><null><null>Calamity
Ganon<null>ÿÿ 100 years ago. <null><null>Don't you recall?

Master Link... <null><null>You really don't remember
anything, do you?

OK!<null> In that case, ask me anything 
you want to!
<null><null><null><null><null>
```

```
I mean...<null><null> Lady Linkle...


You and Lady Mipha fought <null><null><null>Calamity
Ganon<null>ÿÿ 100 years ago. <null><null>Don't you recall?

Lady Linkle... <null><null>You really don't remember
anything, do you?

OK!<null> In that case, ask me anything 
you want to!
<null><null><null><null><null>
```

# Npc_Zora006.msbt - talk19

**LINK!! -> LINKLE!!**

```
Linkle! <null><null>LINK!!<null> My wife, Mei...<null><null>
She came back to me!

I cannot possibly thank you enough!


	But I shall try! Thank you! Thank you!
THANK YOU, TRULY!!
```

```
Linkle! <null><null>LINKLE!!<null> My wife, Mei...<null><null>
She came back to me!

I cannot possibly thank you enough!


	But I shall try! Thank you! Thank you!
THANK YOU, TRULY!!
```

# Npc_Zora007.msbt - talk09

**swordsman -> swordswoman**

```

A swordsman! A traveling one?!<null><null>
So cool!
```

```

A swordswoman! A traveling one?!<null><null>
So cool!
```

# Npc_Zora011.msbt - talk28

**Mister -> Miss**

```
Huh?! <null>Mister, you only have<null><null>
<null><null><null>,(<null>N<null>p<null>c<null>_<null>Z<null>o<null>r<null>a<null>0<null>1<null>1<null>_<null>H<null>a<null>v<null>e<null>F<null>r<null>o<null>g<null><null><null><null>ÿÿ <null><null>hot-footed frogs<null>ÿÿ!
```

```
Huh?! <null>Miss, you only have<null><null>
<null><null><null>,(<null>N<null>p<null>c<null>_<null>Z<null>o<null>r<null>a<null>0<null>1<null>1<null>_<null>H<null>a<null>v<null>e<null>F<null>r<null>o<null>g<null><null><null><null>ÿÿ <null><null>hot-footed frogs<null>ÿÿ!
```

# Npc_Zora034.msbt

## talk00

**sir -> ma'am**

```
<null><null><null>W<null>o<null>r<null>k<null>_<null>0<null>0<null>Yes, sir! <null>East gate is all clear, sir!


...
```

```
<null><null><null>W<null>o<null>r<null>k<null>_<null>0<null>0<null>Yes, ma'am! <null>East gate is all clear, ma'am!


...
```

## talk01

**sir -> ma'am**

```
<null><null><null>W<null>o<null>r<null>k<null>_<null>0<null>0<null>Nothing to report, sir!


Oh... It's you, Linkle.
```

```
<null><null><null>W<null>o<null>r<null>k<null>_<null>0<null>0<null>Nothing to report, ma'am!


Oh... It's you, Linkle.
```

# talk02

**sir -> ma'am**

```
<null><null><null>W<null>o<null>r<null>k<null>_<null>0<null>0<null>Yes, sir! <null><null>Nothing to report, sir!
```

```
<null><null><null>W<null>o<null>r<null>k<null>_<null>0<null>0<null>Yes, ma'am! <null><null>Nothing to report, ma'am!
```

# Npc_Zora035.msbt

## talk02

**Link -> Linkle**

```
...


...


<null>}<null>
Link?!<null>d<null>


<null>}<null>Is that really you?<null>d<null>


The Hylian...<null><null>who stole away our
Lady Mipha! And what's more,
the Champion<null><null> <null>ÿÿwho...
I...<null><null>I cannot forgive you!<null> Not ever!<null><null><null>
```

```
...


...


<null>}<null>
Linkle?!<null>d<null>


<null>}<null>Is that really you?<null>d<null>


The Hylian...<null><null>who stole away our
Lady Mipha! And what's more,
the Champion<null><null> <null>ÿÿwho...
I...<null><null>I cannot forgive you!<null> Not ever!<null><null><null>
```

## talk09

**Link -> Linkle**

```
<null>Link... It seems that...<null>I was wrong
about you.

Seeing <null><null>Divine Beast Vah Ruta<null>ÿÿ's
form there...

Even though we lost Lady Mipha,<null><null>
it seems she can still help you fight
against <null><null><null>Calamity Ganon<null>ÿÿ...
Oh! I am sorry I did not introduce
myself sooner. I am Jiahto.

I am a historian who studies Zora history<null><null>
and preserves it for future generations.
```

```
<null>Linkle... It seems that...<null>I was wrong
about you.

Seeing <null><null>Divine Beast Vah Ruta<null>ÿÿ's
form there...

Even though we lost Lady Mipha,<null><null>
it seems she can still help you fight
against <null><null><null>Calamity Ganon<null>ÿÿ...
Oh! I am sorry I did not introduce
myself sooner. I am Jiahto.

I am a historian who studies Zora history<null><null>
and preserves it for future generations.
```

# talk11

**Link -> Linkle**

```
<null>That is why...<null><null> Link...<null><null> I'd like to ask a
favor of you.
```

```
<null>That is why...<null><null> Linkle...<null><null> I'd like to ask a
favor of you.
```

# talk15

**Link -> Linkle**

```
<null>Hmph...<null><null> Link, eh?
```

```
<null>Hmph...<null><null> Linkle, eh?
```

# Npc_Zora037.msbt - talk14

**man -> woman**

```
<null>You are no ordinary man...


You are always welcome here in
<null><null>Zora's Domain<null>ÿÿ!
```

```
<null>You are no ordinary woman...


You are always welcome here in
<null><null>Zora's Domain<null>ÿÿ!
```

# Npc_ZoraB001.msbt - talk03

**his -> her**

```
Mipha... Dear sister...<null><null><null><null> Are you still
trapped inside the Divine Beast?

Are you supporting Linkle in his fight?<null><null><null><null> 
Is there really nothing more I can do?

I wish you were here to guide me...<null><null><null><null>
I miss you terribly...
```

```
Mipha... Dear sister...<null><null><null><null> Are you still
trapped inside the Divine Beast?

Are you supporting Linkle in her fight?<null><null><null><null> 
Is there really nothing more I can do?

I wish you were here to guide me...<null><null><null><null>
I miss you terribly...
```

### CODE REVIEW

**Comment by linktlh** [comment]
And you threw it onto your switch and tested it correct?

**Comment by anna-is-cute** [comment]
In the process of doing that now, but there will be some lines I can't test.

**Comment by linktlh** [comment]
Comparing the MSBT files the changes look good and correct. I'm good with this being merged.

<h3> ✅ Aproved (1/2) </h3>
<h5>Another approval is required to be merged</h5>

**Comment by anna-is-cute** [comment]
Well, my game freezes when I try using the repo from before my changes or with my changes, so I must be doing something wrong. I'll try to investigate more so I can test.

**Comment by linktlh** [comment]
Give this a try: 

(Removed Download)

I don't currently have CFW on my switch b/c I was playing SSBU with some friends it'll take me a bit to backup my nand so I have a safe nand (which I don't quite have the time)

**Comment by anna-is-cute** [comment]
That zip is empty.

**Comment by linktlh** [comment]
How in the world.. let me try that again..
(Removed Download)

**Comment by anna-is-cute** [comment]
Thanks! I'll try again. For what it's worth, I'll attach the script I used to pack. I'm not sure why it didn't work.

```sh
#!/bin/sh

mkdir -p output/Bootup_USen/Message
mkdir -p output/Bootup_EUen/Message
mkdir -p temp/DemoMsg
mkdir -p temp/ActorType
mkdir -p temp/LayoutMsg
mkdir -p temp/QuestMsg
mkdir -p temp/ShoutMsg
mkdir -p temp/StaticMsg
mkdir -p temp/Tips
mkdir -p temp/EventFlowMsg
cp ActorType/* temp/ActorType
cp DemoMsg/* temp/DemoMsg
cp LayoutMsg/* temp/LayoutMsg
cp QuestMsg/* temp/QuestMsg
cp ShoutMsg/* temp/ShoutMsg
cp StaticMsg/* temp/StaticMsg
cp Tips/* temp/Tips
cp EventFlowMsg/* temp/EventFlowMsg

sarctool create temp Msg_USen.product.ssarc

cp Msg_USen.product.ssarc output/Bootup_EUen/Message/Msg_EUen.product.ssarc
mv Msg_USen.product.ssarc output/Bootup_USen/Message/

cd output || exit
sarctool create Bootup_USen Bootup_USen.pack
sarctool create Bootup_EUen Bootup_EUen.pack
rm -r ../temp/
rm -r Bootup_USen/
rm -r Bootup_EUen/
```

**Comment by anna-is-cute** [comment]
@linktlh Did you compile with my changes checked out? The first line in the PR isn't changed: "For he who saved the domain..."

**Comment by linktlh** [comment]
Shoot compiled the wrong src I apologize xD
That's the really broken testing src.
[ManualPR_Build.zip](https://github.com/linktlh/Linkle-Dialog-Fixes/files/2916511/ManualPR_Build.zip)

This SHOULD be the right one.

**Comment by anna-is-cute** [comment]
New one that I caught looking for the ones I already fixed: Npc_Zora011.msbt talk00.

```
What is it?!<null> Oh! Hey, mister!
```

```
What is it?!<null> Oh! Hey, miss!
```

And also "Heya, mister!" to "Hey, miss!" I'll push next.

And then Npc_Zora001.msbt talk06:

```
<null>-Yes, sir! <null><null>Nothing to report, sir!
```

```
<null>-Yes, ma'am! <null><null>Nothing to report, ma'am!
```

**Comment by anna-is-cute** [comment]
The ones I was able to test looked good.

**Comment by linktlh** [comment]
From what I can tell it seems like this is perfectly fine to merge. I’m just going to ignore the normal 2 user review.

**Comment by linktlh** [comment]
Oh, and btw, it's because you tried to use sarcTOOL instead of sarc
pip install sarc
(python)
Edit: Actually apparently I made my script using sarctool.. honestly I don't know why that works sarctool is really broken. But give sarc a shot.

**Comment by anna-is-cute** [comment]
```
% sha256sum /home/jkcclemens/.pyenv/versions/3.7.1/bin/{sarc,sarctool}                           ret: 0
ca53fda86eae85120845545c32589e521190f6c5b3ef91eeda775b31e1001bd2  /home/jkcclemens/.pyenv/versions/3.7.1/bin/sarc
ca53fda86eae85120845545c32589e521190f6c5b3ef91eeda775b31e1001bd2  /home/jkcclemens/.pyenv/versions/3.7.1/bin/sarctool
```

**Pull request merged**
