### PR TITLE
Restructure all files.

### PR DESCRIPTION
**Pull request by polarbunny**
As suggested. Unsure what to do about packing scripts though, any thoughts?

### CODE REVIEW

**Review by linktlh — CHANGES_REQUESTED** [review]
This would be more confusing than helpful Ex: which ones are switch v wii u? what is msyt files (switch or wii u) what are msbt files (switch for wii u?) why have both msbt and msyt? if we switch off msbt there's no reasons to have both.

**Comment by polarbunny** [comment]
Just to clarify, the msyt files were made using the xmsbt files as a source, the wiiu and switch folders are just msbt files of the respective branches. I left in xmsbt because I didnt know what everyone would wan't with it.

I agree it's not the most self-explanatory.

**Comment by anna-is-cute** [comment]
Just to clarify, XMSBT is version-dependent just like MSYT. The MSYT files will soon not be, though. I doubt this will matter because of the repo changes happening soon, though.

**Comment by polarbunny** [comment]
Closing.

**Pull request closed without merging**
